name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build The Docs
        run: |
          npm run build:docs
          mkdir docs # Create docs folder if not existing
          # Copy the built files to the docs folder
          cp -R path_to_build_files/* docs/

      - name: Deploy to gh-pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout --orphan gh-pages # Create gh-pages branch if not existing
          git reset --hard
          git clean -df
          git add docs/
          git commit -m 'Deployed docs to gh-pages'
          git push origin HEAD:gh-pages
