name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Pages
        run: npm run build:docs

      - name: Verify 'docs' directory
        run: ls -l ./docs  # Check if 'docs' directory exists and contains files (optional)

      - name: Upload 'docs' artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download 'docs' artifact
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ./docs  # Download 'docs' artifact to the current job's workspace
      - name: Verify 'docs' directory
        run: ls -l ./docs  # Check if 'docs' directory exists and contains files (optional)
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
